version: "3.9"

services:
  core:
    platform: linux/x86_64  # https://github.com/GrahamDumpleton/wrapt/issues/199#issuecomment-1054696160
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    env_file:
      - ../src/config/.env.local
